name: Optimize images

on:
  workflow_dispatch:
  push:
    paths:
      - 'images/**'

jobs:
  optimize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow git-filter-repo

      - name: Convert images to WebP and resize
        run: python scripts/convert_images.py --deleted-log /tmp/deleted_images.txt

      - name: Commit optimized assets
        id: commit
        run: |
          if [[ -n "$(git status --porcelain images)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add images || true
            git commit -m "Optimize images"
            echo "committed=true" >> "$GITHUB_OUTPUT"
          else
            echo "No image changes to commit."
            echo "committed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Remove originals from Git history
        if: steps.commit.outputs.committed == 'true'
        run: |
          if [ -s /tmp/deleted_images.txt ]; then
            git filter-repo --force --invert-paths --paths-from-file /tmp/deleted_images.txt
          else
            echo "No originals required history cleanup."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
